name: "Dive CI"

on: [push]

jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dive
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: ps2dev/ps2dev:v1.2.0
          config-file: ${{ github.workspace }}/.dive-ci.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker pull ps2dev/ps2dev:latest
          docker history ps2dev/ps2dev:latest | awk 'NR>1 {print $1}' | xargs docker inspect --format '{{ ((index .ContainerConfig.Cmd ) 0) }}'
