name: CI-Docker

on:
  push:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Upload latest Docker version
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.GITHUB_REPOSITORY }}
        build_args: BASE_DOCKER_IMAGE=ps2dev/ps2sdk-ports:latest
        tag_with_ref: true
